#' Creates a simple example ASV table
#'
#' @returns A simple ASV table
#' @export
#'
#' @examples
#' makeExampleSeqtab()
makeExampleSeqtab <- function(){
  tibble::tibble(SampleID=c("HC1", "HC2", "HC3", "Sick1", "Sick2", "Sick3", "Sick4", "ExtNegControl1", "ExtNegControl2", "PCRNegControl1", "PCRNegControl2", "PosControl1"),
                 TACGGAGGGTGCGAGCGTTAATCGGAATAACTGGGCGTAAAGGGCACGCAGGCGGTTATTTAAGTGAGGTGTGAAAGCCCTGGGCTTAACCTAGGAATTGCATTTCAGACTGGGTAACTAGAGTACTTTAGGGAGGGGTAGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAATACCGAAGGCGAAGGCAGCCCCTTGGGAATGTACTGACGCTCATGTGCGAAAGCGTGGGGAGCAAACAGG=c(1856, 25732, 3385, 29939, 29954, 29724, 1, 12, 10, 0, 1, 10005),
                 TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCTGGAGATTAAGTGTGTTGTGAAATGTAGACGCTCAACGTCTGAATTGCAGCGCATACTGGTTTCCTTGAGTACGCACAACGTTGGCGGAATTCGTCGTGTAGCGGTGAAATGCTTAGATATGACGAAGAACTCCGATTGCGAAGGCAGCTGACGGGAGCGCAACTGACGCTTAAGCTCGAAGGTGCGGGTATCAAACAGG=c(11652, 4775, 6760, 26217, 16142, 2771, 2, 5, 3, 2, 1, 100024),
                 TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGAAAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGCAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGATGTGCGAAAGCGTGGGGATCAAACAGG=c(13681, 2902, 6184, 18965, 9656, 26380, 0, 10, 2, 0, 1, 10036),
                 TACGGAGGGTGCGAGCGTTAATCGGAATAACTGGGCGTAAAGGGCACGCAGGCGGTTATTTAAGTGAGGTGTGAAAGCCCCGGGCTTAACCTGGGAATTGCATTTCAGACTGGGTAACTAGAGTACTTTAGGGAGGGGTAGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAATACCGAAGGCGAAGGCAGCCCCTTGGGAATGTACTGACGCTCATGTGCGAAAGCGTGGGGAGCAAACAGG=c(2994, 1628, 569, 4483, 9373, 7803, 5, 21, 1, 0, 1, 0),
                 TACGTAGGTCCCGAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTAGATAAGTCTGAAGTTAAAGGCTGTGGCTTAACCATAGTAGGCTTTGGAAACTGTTTAACTTGAGTGCAAGAGGGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCGGTGGCGAAAGCGGCTCTCTGGCTTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAAACAGG=c(9111, 1061, 7081, 3018, 3221, 8003, 1, 6, 0, 1, 1, 12040),
                 TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGACGATTAAGTCAGCTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGAAACTGGTTGTCTTGAGTGCACGCAGGGATGTTGGAATTCATGGTGTAGCGGTGAAATGCTTAGATATCATGAAGAACTCCGATCGCGAAGGCATATGTCTGGAGTGCAACTGACGCTGAGGCTCGAAAGTGCGGGTATCGAACAGG=c(3995, 13536, 8358, 217, 9506, 8157, 0, 0, 1, 1, 1, 0),
                 TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTGTTAAGTCAGCGGTTAAAGGGTGTGGCTCAACCATGCATTGCCGTTGAAACTGGCGATCTTGAGTGCAGACAGGGATGCCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATCGCGAAGGCAGGTGTCCGGGCTGCAACTGACGCTGAGGCTCGAAAGTGTGGGTATCAAACAGG=c(10821, 6216, 8780, 1599, 4237, 13010, 0, 0, 1, 1, 1, 0),
                 TACGAAGGGTGCAAGCGTTACTCGGAATTACTGGGCGTAAAGCGTGCGTAGGTGGTCGTTTAAGTCCGTTGTGAAAGCCCTGGGCTCAACCTGGGAACTGCAGTGGATACTGGGCGACTAGAGTGTGGTAGAGGGTAGCGGAATTCCTGGTGTAGCAGTGAAATGCGTAGAGATCAGGAGGAACATCCATGGCGAAGGCAGCTACCTGGACCAACACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGG=c(3937, 4089, 2907, 12441, 294, 8469, 0, 0, 1, 1, 1, 0),
                 TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTATTAAGTCAGTGGTGAAAGACGGTGGCTCAACCATCGTTAGCCATTGAAACTGGTAGTCTTGAGTGCAGACAGGGATGCTGGAACTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGATGAACTCCAATCGCGAAGGCAGGTGTCCGGGCTGCAACTGACGCTGAGGCTCGAAAGTGTGGGTATCAAACAGG=c(4, 6, 8, 6, 6, 7, 1, 0, 1, 1, 1, 0))
}
